// Code generated by protoc-gen-go.
// source: CommonMessages.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	CommonMessages.proto
	CommonModelMessages.proto
	OpenApiMessages.proto
	OpenApiModelMessages.proto

It has these top-level messages:
	ProtoMessage
	ProtoErrorRes
	ProtoHeartbeatEvent
	ProtoPingReq
	ProtoPingRes
	ProtoIntRange
	ProtoLongRange
	ProtoDoubleRange
	ProtoOAAuthReq
	ProtoOAAuthRes
	ProtoOASubscribeForTradingEventsReq
	ProtoOASubscribeForTradingEventsRes
	ProtoOAUnsubscribeFromTradingEventsReq
	ProtoOAUnsubscribeFromTradingEventsRes
	ProtoOAGetSubscribedAccountsReq
	ProtoOAGetSubscribedAccountsRes
	ProtoOAExecutionEvent
	ProtoOACreateOrderReq
	ProtoOACancelOrderReq
	ProtoOAClosePositionReq
	ProtoOAAmendPositionStopLossTakeProfitReq
	ProtoOAAmendOrderReq
	ProtoOASubscribeForSpotsReq
	ProtoOASubscribeForSpotsRes
	ProtoOAUnsubscribeFromSpotsReq
	ProtoOAUnsubscribeFromSpotsRes
	ProtoOAGetSpotSubscriptionReq
	ProtoOAGetSpotSubscriptionRes
	ProtoOAGetAllSpotSubscriptionsReq
	ProtoOAGetAllSpotSubscriptionsRes
	ProtoOASpotEvent
	ProtoOAPartnerDetails
	ProtoOAOrder
	ProtoOAPosition
	ProtoOAClosePositionDetails
	ProtoOASpotSubscription
	ProtoOASubscribedSpotSymbol
	ProtoOATrendbar
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ProtoMessage struct {
	PayloadType      *uint32 `protobuf:"varint,1,req,name=payloadType" json:"payloadType,omitempty"`
	Payload          []byte  `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	ClientMsgId      *string `protobuf:"bytes,3,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoMessage) Reset()                    { *m = ProtoMessage{} }
func (m *ProtoMessage) String() string            { return proto.CompactTextString(m) }
func (*ProtoMessage) ProtoMessage()               {}
func (*ProtoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMessage) GetPayloadType() uint32 {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return 0
}

func (m *ProtoMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ProtoMessage) GetClientMsgId() string {
	if m != nil && m.ClientMsgId != nil {
		return *m.ClientMsgId
	}
	return ""
}

type ProtoErrorRes struct {
	PayloadType      *ProtoPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=50" json:"payloadType,omitempty"`
	ErrorCode        *string           `protobuf:"bytes,2,req,name=errorCode" json:"errorCode,omitempty"`
	Description      *string           `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProtoErrorRes) Reset()                    { *m = ProtoErrorRes{} }
func (m *ProtoErrorRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoErrorRes) ProtoMessage()               {}
func (*ProtoErrorRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_ProtoErrorRes_PayloadType ProtoPayloadType = ProtoPayloadType_ERROR_RES

func (m *ProtoErrorRes) GetPayloadType() ProtoPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoErrorRes_PayloadType
}

func (m *ProtoErrorRes) GetErrorCode() string {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ""
}

func (m *ProtoErrorRes) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type ProtoHeartbeatEvent struct {
	PayloadType      *ProtoPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=51" json:"payloadType,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProtoHeartbeatEvent) Reset()                    { *m = ProtoHeartbeatEvent{} }
func (m *ProtoHeartbeatEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtoHeartbeatEvent) ProtoMessage()               {}
func (*ProtoHeartbeatEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_ProtoHeartbeatEvent_PayloadType ProtoPayloadType = ProtoPayloadType_HEARTBEAT_EVENT

func (m *ProtoHeartbeatEvent) GetPayloadType() ProtoPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoHeartbeatEvent_PayloadType
}

type ProtoPingReq struct {
	PayloadType      *ProtoPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=52" json:"payloadType,omitempty"`
	Timestamp        *uint64           `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProtoPingReq) Reset()                    { *m = ProtoPingReq{} }
func (m *ProtoPingReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoPingReq) ProtoMessage()               {}
func (*ProtoPingReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_ProtoPingReq_PayloadType ProtoPayloadType = ProtoPayloadType_PING_REQ

func (m *ProtoPingReq) GetPayloadType() ProtoPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoPingReq_PayloadType
}

func (m *ProtoPingReq) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type ProtoPingRes struct {
	PayloadType      *ProtoPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoPayloadType,def=53" json:"payloadType,omitempty"`
	Timestamp        *uint64           `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProtoPingRes) Reset()                    { *m = ProtoPingRes{} }
func (m *ProtoPingRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoPingRes) ProtoMessage()               {}
func (*ProtoPingRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_ProtoPingRes_PayloadType ProtoPayloadType = ProtoPayloadType_PING_RES

func (m *ProtoPingRes) GetPayloadType() ProtoPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoPingRes_PayloadType
}

func (m *ProtoPingRes) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoMessage)(nil), "ProtoMessage")
	proto.RegisterType((*ProtoErrorRes)(nil), "ProtoErrorRes")
	proto.RegisterType((*ProtoHeartbeatEvent)(nil), "ProtoHeartbeatEvent")
	proto.RegisterType((*ProtoPingReq)(nil), "ProtoPingReq")
	proto.RegisterType((*ProtoPingRes)(nil), "ProtoPingRes")
}

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xc9, 0x26, 0x68, 0xe3, 0xe6, 0x58, 0x26, 0x38, 0x3d, 0x8d, 0x9e, 0x7a, 0x2a, 0xea,
	0x45, 0xf0, 0xb6, 0x8d, 0xb0, 0xed, 0xb0, 0x59, 0xb3, 0xe2, 0xc1, 0xcb, 0x88, 0xed, 0xa3, 0x44,
	0x9a, 0xa4, 0x26, 0x41, 0xdc, 0x7f, 0xe3, 0x9f, 0x6a, 0xdb, 0x15, 0x64, 0xc3, 0xc3, 0xbc, 0x3d,
	0xbe, 0xf7, 0xf2, 0xfb, 0x3e, 0xf2, 0x1e, 0xbe, 0x9c, 0x6a, 0x29, 0xb5, 0x5a, 0x82, 0xb5, 0x3c,
	0x03, 0x1b, 0x16, 0x46, 0x3b, 0x7d, 0x73, 0xdd, 0xa8, 0x3a, 0x85, 0x7c, 0xbf, 0xe5, 0x2f, 0x70,
	0x27, 0xaa, 0x8a, 0x46, 0x26, 0x03, 0x7c, 0x5e, 0xf0, 0x6d, 0xae, 0x79, 0x1a, 0x6f, 0x0b, 0x18,
	0xa2, 0x51, 0x2b, 0xe8, 0x92, 0x1e, 0x3e, 0x6d, 0xc4, 0x61, 0x6b, 0x84, 0x82, 0x4e, 0x35, 0x95,
	0xe4, 0x02, 0x94, 0x5b, 0xda, 0x6c, 0x91, 0x0e, 0xdb, 0xa5, 0xe8, 0xf9, 0xef, 0xb8, 0x5b, 0xa3,
	0xa8, 0x31, 0xda, 0x30, 0xb0, 0xe4, 0xee, 0x90, 0x85, 0x82, 0x8b, 0xfb, 0x7e, 0x58, 0x0f, 0x45,
	0xbf, 0x8d, 0x47, 0x8f, 0x32, 0xf6, 0xc4, 0x36, 0x8c, 0xae, 0x49, 0x1f, 0x7b, 0x50, 0x3d, 0x9f,
	0x96, 0x51, 0x4b, 0xaf, 0x56, 0xe0, 0x55, 0x5e, 0x29, 0xd8, 0xc4, 0x88, 0xc2, 0x09, 0xad, 0x1a,
	0xaf, 0x15, 0x1e, 0xd4, 0x98, 0x39, 0x70, 0xe3, 0xde, 0x80, 0x3b, 0xfa, 0x59, 0xa6, 0x21, 0x0f,
	0x47, 0x3a, 0xf6, 0xe6, 0x74, 0xcc, 0xe2, 0x09, 0x1d, 0xc7, 0x1b, 0xfa, 0x42, 0x57, 0xb1, 0xbf,
	0x6e, 0xbe, 0x21, 0x12, 0x2a, 0x63, 0xf0, 0x41, 0x6e, 0x8f, 0x04, 0x9d, 0x45, 0x8b, 0xd5, 0xac,
	0x4c, 0xfe, 0x5c, 0x25, 0x77, 0x42, 0x82, 0x75, 0x5c, 0x16, 0x75, 0xf2, 0x93, 0x03, 0xa8, 0xfd,
	0x37, 0x74, 0xfd, 0x07, 0x74, 0x32, 0xc3, 0x7e, 0xa2, 0x65, 0xf8, 0xe5, 0x0c, 0x4f, 0xc1, 0xec,
	0xb6, 0x98, 0xe8, 0x7c, 0x57, 0x84, 0x49, 0xbd, 0x68, 0x3b, 0xb9, 0x9a, 0x6a, 0xe5, 0xb8, 0x50,
	0x60, 0xf6, 0x0f, 0x22, 0x42, 0xaf, 0x6d, 0x69, 0xb3, 0x6f, 0x84, 0x7e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x0e, 0x25, 0x45, 0xcb, 0x2b, 0x02, 0x00, 0x00,
}
