// Code generated by protoc-gen-go.
// source: CommonModelMessages.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// --- COMMON API 50 - 69 --- [1 - 49 reserved for traffic intensive messages]
type ProtoPayloadType int32

const (
	ProtoPayloadType_ERROR_RES       ProtoPayloadType = 50
	ProtoPayloadType_HEARTBEAT_EVENT ProtoPayloadType = 51
	ProtoPayloadType_PING_REQ        ProtoPayloadType = 52
	ProtoPayloadType_PING_RES        ProtoPayloadType = 53
)

var ProtoPayloadType_name = map[int32]string{
	50: "ERROR_RES",
	51: "HEARTBEAT_EVENT",
	52: "PING_REQ",
	53: "PING_RES",
}
var ProtoPayloadType_value = map[string]int32{
	"ERROR_RES":       50,
	"HEARTBEAT_EVENT": 51,
	"PING_REQ":        52,
	"PING_RES":        53,
}

func (x ProtoPayloadType) Enum() *ProtoPayloadType {
	p := new(ProtoPayloadType)
	*p = x
	return p
}
func (x ProtoPayloadType) String() string {
	return proto.EnumName(ProtoPayloadType_name, int32(x))
}
func (x *ProtoPayloadType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoPayloadType_value, data, "ProtoPayloadType")
	if err != nil {
		return err
	}
	*x = ProtoPayloadType(value)
	return nil
}
func (ProtoPayloadType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// COMMON error codes 1 - 99
type ProtoErrorCode int32

const (
	ProtoErrorCode_UNKNOWN_ERROR           ProtoErrorCode = 1
	ProtoErrorCode_UNSUPPORTED_MESSAGE     ProtoErrorCode = 2
	ProtoErrorCode_INVALID_REQUEST         ProtoErrorCode = 3
	ProtoErrorCode_WRONG_PASSWORD          ProtoErrorCode = 4
	ProtoErrorCode_TIMEOUT_ERROR           ProtoErrorCode = 5
	ProtoErrorCode_ENTITY_NOT_FOUND        ProtoErrorCode = 6
	ProtoErrorCode_CANT_ROUTE_REQUEST      ProtoErrorCode = 7
	ProtoErrorCode_FRAME_TOO_LONG          ProtoErrorCode = 8
	ProtoErrorCode_MARKET_CLOSED           ProtoErrorCode = 9
	ProtoErrorCode_CONCURRENT_MODIFICATION ProtoErrorCode = 10
)

var ProtoErrorCode_name = map[int32]string{
	1:  "UNKNOWN_ERROR",
	2:  "UNSUPPORTED_MESSAGE",
	3:  "INVALID_REQUEST",
	4:  "WRONG_PASSWORD",
	5:  "TIMEOUT_ERROR",
	6:  "ENTITY_NOT_FOUND",
	7:  "CANT_ROUTE_REQUEST",
	8:  "FRAME_TOO_LONG",
	9:  "MARKET_CLOSED",
	10: "CONCURRENT_MODIFICATION",
}
var ProtoErrorCode_value = map[string]int32{
	"UNKNOWN_ERROR":           1,
	"UNSUPPORTED_MESSAGE":     2,
	"INVALID_REQUEST":         3,
	"WRONG_PASSWORD":          4,
	"TIMEOUT_ERROR":           5,
	"ENTITY_NOT_FOUND":        6,
	"CANT_ROUTE_REQUEST":      7,
	"FRAME_TOO_LONG":          8,
	"MARKET_CLOSED":           9,
	"CONCURRENT_MODIFICATION": 10,
}

func (x ProtoErrorCode) Enum() *ProtoErrorCode {
	p := new(ProtoErrorCode)
	*p = x
	return p
}
func (x ProtoErrorCode) String() string {
	return proto.EnumName(ProtoErrorCode_name, int32(x))
}
func (x *ProtoErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoErrorCode_value, data, "ProtoErrorCode")
	if err != nil {
		return err
	}
	*x = ProtoErrorCode(value)
	return nil
}
func (ProtoErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ProtoTradeSide int32

const (
	ProtoTradeSide_BUY  ProtoTradeSide = 1
	ProtoTradeSide_SELL ProtoTradeSide = 2
)

var ProtoTradeSide_name = map[int32]string{
	1: "BUY",
	2: "SELL",
}
var ProtoTradeSide_value = map[string]int32{
	"BUY":  1,
	"SELL": 2,
}

func (x ProtoTradeSide) Enum() *ProtoTradeSide {
	p := new(ProtoTradeSide)
	*p = x
	return p
}
func (x ProtoTradeSide) String() string {
	return proto.EnumName(ProtoTradeSide_name, int32(x))
}
func (x *ProtoTradeSide) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoTradeSide_value, data, "ProtoTradeSide")
	if err != nil {
		return err
	}
	*x = ProtoTradeSide(value)
	return nil
}
func (ProtoTradeSide) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ProtoQuoteType int32

const (
	ProtoQuoteType_BID ProtoQuoteType = 1
	ProtoQuoteType_ASK ProtoQuoteType = 2
)

var ProtoQuoteType_name = map[int32]string{
	1: "BID",
	2: "ASK",
}
var ProtoQuoteType_value = map[string]int32{
	"BID": 1,
	"ASK": 2,
}

func (x ProtoQuoteType) Enum() *ProtoQuoteType {
	p := new(ProtoQuoteType)
	*p = x
	return p
}
func (x ProtoQuoteType) String() string {
	return proto.EnumName(ProtoQuoteType_name, int32(x))
}
func (x *ProtoQuoteType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoQuoteType_value, data, "ProtoQuoteType")
	if err != nil {
		return err
	}
	*x = ProtoQuoteType(value)
	return nil
}
func (ProtoQuoteType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type ProtoTimeInForce int32

const (
	ProtoTimeInForce_GOOD_TILL_DATE      ProtoTimeInForce = 1
	ProtoTimeInForce_GOOD_TILL_CANCEL    ProtoTimeInForce = 2
	ProtoTimeInForce_IMMEDIATE_OR_CANCEL ProtoTimeInForce = 3
)

var ProtoTimeInForce_name = map[int32]string{
	1: "GOOD_TILL_DATE",
	2: "GOOD_TILL_CANCEL",
	3: "IMMEDIATE_OR_CANCEL",
}
var ProtoTimeInForce_value = map[string]int32{
	"GOOD_TILL_DATE":      1,
	"GOOD_TILL_CANCEL":    2,
	"IMMEDIATE_OR_CANCEL": 3,
}

func (x ProtoTimeInForce) Enum() *ProtoTimeInForce {
	p := new(ProtoTimeInForce)
	*p = x
	return p
}
func (x ProtoTimeInForce) String() string {
	return proto.EnumName(ProtoTimeInForce_name, int32(x))
}
func (x *ProtoTimeInForce) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoTimeInForce_value, data, "ProtoTimeInForce")
	if err != nil {
		return err
	}
	*x = ProtoTimeInForce(value)
	return nil
}
func (ProtoTimeInForce) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type ProtoIntRange struct {
	From             *int32 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To               *int32 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoIntRange) Reset()                    { *m = ProtoIntRange{} }
func (m *ProtoIntRange) String() string            { return proto.CompactTextString(m) }
func (*ProtoIntRange) ProtoMessage()               {}
func (*ProtoIntRange) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ProtoIntRange) GetFrom() int32 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *ProtoIntRange) GetTo() int32 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

type ProtoLongRange struct {
	From             *int64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To               *int64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProtoLongRange) Reset()                    { *m = ProtoLongRange{} }
func (m *ProtoLongRange) String() string            { return proto.CompactTextString(m) }
func (*ProtoLongRange) ProtoMessage()               {}
func (*ProtoLongRange) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ProtoLongRange) GetFrom() int64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *ProtoLongRange) GetTo() int64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

type ProtoDoubleRange struct {
	From             *float64 `protobuf:"fixed64,1,opt,name=from" json:"from,omitempty"`
	To               *float64 `protobuf:"fixed64,2,opt,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoDoubleRange) Reset()                    { *m = ProtoDoubleRange{} }
func (m *ProtoDoubleRange) String() string            { return proto.CompactTextString(m) }
func (*ProtoDoubleRange) ProtoMessage()               {}
func (*ProtoDoubleRange) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ProtoDoubleRange) GetFrom() float64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *ProtoDoubleRange) GetTo() float64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoIntRange)(nil), "ProtoIntRange")
	proto.RegisterType((*ProtoLongRange)(nil), "ProtoLongRange")
	proto.RegisterType((*ProtoDoubleRange)(nil), "ProtoDoubleRange")
	proto.RegisterEnum("ProtoPayloadType", ProtoPayloadType_name, ProtoPayloadType_value)
	proto.RegisterEnum("ProtoErrorCode", ProtoErrorCode_name, ProtoErrorCode_value)
	proto.RegisterEnum("ProtoTradeSide", ProtoTradeSide_name, ProtoTradeSide_value)
	proto.RegisterEnum("ProtoQuoteType", ProtoQuoteType_name, ProtoQuoteType_value)
	proto.RegisterEnum("ProtoTimeInForce", ProtoTimeInForce_name, ProtoTimeInForce_value)
}

var fileDescriptor1 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0x87, 0x95, 0x66, 0x63, 0x9b, 0x45, 0x87, 0xf1, 0x10, 0x1b, 0x82, 0x0b, 0x54, 0x6e, 0x46,
	0x85, 0x7a, 0xc1, 0x9f, 0x07, 0x70, 0x63, 0xb7, 0x58, 0x4d, 0xec, 0xcc, 0x76, 0x56, 0x8d, 0x1b,
	0x2b, 0xb4, 0xa6, 0xaa, 0xd4, 0xc4, 0x53, 0x9a, 0x49, 0xec, 0x6d, 0x78, 0x3e, 0x9e, 0x02, 0xbb,
	0x8b, 0xa0, 0xd2, 0xb8, 0x3b, 0x49, 0xbe, 0x7c, 0xe7, 0xfc, 0xec, 0x03, 0x5e, 0x25, 0xae, 0xaa,
	0x5c, 0x9d, 0xb9, 0xa5, 0xdd, 0x64, 0x76, 0xbb, 0x2d, 0x57, 0x76, 0x3b, 0xba, 0x6d, 0x5c, 0xeb,
	0x06, 0xef, 0x41, 0x3f, 0x0f, 0x05, 0xab, 0x5b, 0x59, 0xd6, 0x2b, 0x8b, 0x9e, 0x82, 0x83, 0x1f,
	0x8d, 0xab, 0x2e, 0xa2, 0xb7, 0xd1, 0xe5, 0x21, 0x02, 0xa0, 0xd7, 0xba, 0x8b, 0x5e, 0xa8, 0x07,
	0x43, 0x70, 0xba, 0x43, 0x53, 0x57, 0xaf, 0x1e, 0xb3, 0xf1, 0x1e, 0x1b, 0x0f, 0x3e, 0x00, 0xb8,
	0x63, 0x89, 0xbb, 0xfb, 0xbe, 0xb1, 0x8f, 0xe9, 0x68, 0x8f, 0x8e, 0x86, 0xb2, 0xa3, 0xf3, 0xf2,
	0x7e, 0xe3, 0xca, 0xa5, 0xbe, 0xbf, 0xb5, 0xa8, 0x0f, 0x4e, 0xa8, 0x94, 0x42, 0x1a, 0x49, 0x15,
	0xfc, 0x88, 0xce, 0xc0, 0xb3, 0xaf, 0x14, 0x4b, 0x3d, 0xa6, 0x58, 0x1b, 0x7a, 0x4d, 0xb9, 0x86,
	0x9f, 0xbc, 0xf1, 0x38, 0x67, 0x7c, 0xea, 0x91, 0x2b, 0xf8, 0x79, 0xef, 0x49, 0xc1, 0x2f, 0xc3,
	0xdf, 0x51, 0x37, 0x2e, 0x6d, 0x1a, 0xd7, 0x24, 0x3e, 0x3a, 0x7a, 0x0e, 0xfa, 0x05, 0x9f, 0x71,
	0x31, 0xe7, 0x66, 0xa7, 0x86, 0x11, 0x3a, 0x07, 0x67, 0x05, 0x57, 0x45, 0x9e, 0x0b, 0xa9, 0x29,
	0x31, 0x19, 0x55, 0x0a, 0x4f, 0x29, 0xec, 0x85, 0x7e, 0x8c, 0x5f, 0xe3, 0x94, 0x91, 0x60, 0x2f,
	0xa8, 0xd2, 0x30, 0x46, 0x08, 0x9c, 0xce, 0xa5, 0xf0, 0x2d, 0x72, 0xac, 0xd4, 0x5c, 0x48, 0x02,
	0x0f, 0x82, 0x54, 0xb3, 0x8c, 0x8a, 0x42, 0x77, 0xd2, 0x43, 0xf4, 0x02, 0x40, 0x3f, 0x1f, 0xd3,
	0x37, 0x86, 0x0b, 0x6d, 0x26, 0xa2, 0xe0, 0x04, 0x3e, 0x41, 0x2f, 0x01, 0x4a, 0x30, 0xd7, 0x46,
	0x7a, 0x94, 0xfe, 0x95, 0x1e, 0x05, 0xe9, 0x44, 0xe2, 0x8c, 0x1a, 0x2d, 0x84, 0x49, 0xbd, 0x1d,
	0x1e, 0x07, 0x69, 0x86, 0xe5, 0x8c, 0x6a, 0x93, 0xa4, 0x42, 0x51, 0x02, 0x4f, 0xd0, 0x6b, 0x70,
	0x9e, 0x08, 0x9e, 0x14, 0x52, 0x7a, 0xb7, 0xc9, 0x04, 0x61, 0x13, 0x96, 0x60, 0xcd, 0x04, 0x87,
	0x60, 0xf8, 0xae, 0xcb, 0xaa, 0x9b, 0x72, 0x69, 0xd5, 0xda, 0x67, 0x3d, 0x02, 0xf1, 0xb8, 0xb8,
	0xf1, 0x09, 0x8f, 0xc1, 0x81, 0xa2, 0x69, 0x0a, 0x7b, 0xc3, 0x41, 0x07, 0x5d, 0xdd, 0xb9, 0xd6,
	0xee, 0xce, 0x38, 0x40, 0x8c, 0x78, 0xc8, 0x17, 0x58, 0xcd, 0x3c, 0x53, 0x74, 0x37, 0xa1, 0xd7,
	0x95, 0x65, 0xf5, 0xc4, 0x35, 0x0b, 0x1b, 0x06, 0x9c, 0x0a, 0x41, 0x8c, 0x66, 0x69, 0x6a, 0x08,
	0xd6, 0xd4, 0xff, 0xe0, 0x23, 0xfe, 0x7b, 0xe7, 0x63, 0x25, 0xd4, 0x77, 0x08, 0xa7, 0xc9, 0xb2,
	0x8c, 0x12, 0xe6, 0x21, 0xe3, 0xaf, 0xae, 0xfb, 0x10, 0x8f, 0x25, 0xb8, 0x5c, 0xb8, 0x6a, 0xf4,
	0xb3, 0x0d, 0xf3, 0x35, 0x0f, 0xab, 0xb7, 0x70, 0x9b, 0x87, 0x62, 0xb4, 0xd8, 0x6d, 0xe7, 0x76,
	0x54, 0x85, 0xfd, 0x1c, 0xbf, 0x49, 0x5c, 0xdd, 0x96, 0xeb, 0xda, 0x36, 0xff, 0xd9, 0xda, 0x3c,
	0xfa, 0x16, 0x57, 0xdb, 0xd5, 0xaf, 0x28, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x38, 0xce,
	0xe3, 0xd5, 0x02, 0x00, 0x00,
}
