// Code generated by protoc-gen-go.
// source: OpenApiMessages.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// * Authentication request
type ProtoOAAuthReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2000" json:"payloadType,omitempty"`
	ClientId         *string             `protobuf:"bytes,2,req,name=clientId" json:"clientId,omitempty"`
	ClientSecret     *string             `protobuf:"bytes,3,req,name=clientSecret" json:"clientSecret,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAAuthReq) Reset()                    { *m = ProtoOAAuthReq{} }
func (m *ProtoOAAuthReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAAuthReq) ProtoMessage()               {}
func (*ProtoOAAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

const Default_ProtoOAAuthReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_AUTH_REQ

func (m *ProtoOAAuthReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAAuthReq_PayloadType
}

func (m *ProtoOAAuthReq) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *ProtoOAAuthReq) GetClientSecret() string {
	if m != nil && m.ClientSecret != nil {
		return *m.ClientSecret
	}
	return ""
}

// * Authentication response
type ProtoOAAuthRes struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2001" json:"payloadType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAAuthRes) Reset()                    { *m = ProtoOAAuthRes{} }
func (m *ProtoOAAuthRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAAuthRes) ProtoMessage()               {}
func (*ProtoOAAuthRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

const Default_ProtoOAAuthRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_AUTH_RES

func (m *ProtoOAAuthRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAAuthRes_PayloadType
}

// * Request which subscribes for trading events for specified account
type ProtoOASubscribeForTradingEventsReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2002" json:"payloadType,omitempty"`
	AccountId        *int64              `protobuf:"varint,2,req,name=accountId" json:"accountId,omitempty"`
	AccessToken      *string             `protobuf:"bytes,3,req,name=accessToken" json:"accessToken,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOASubscribeForTradingEventsReq) Reset()         { *m = ProtoOASubscribeForTradingEventsReq{} }
func (m *ProtoOASubscribeForTradingEventsReq) String() string { return proto.CompactTextString(m) }
func (*ProtoOASubscribeForTradingEventsReq) ProtoMessage()    {}
func (*ProtoOASubscribeForTradingEventsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{2}
}

const Default_ProtoOASubscribeForTradingEventsReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_SUBSCRIBE_FOR_TRADING_EVENTS_REQ

func (m *ProtoOASubscribeForTradingEventsReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOASubscribeForTradingEventsReq_PayloadType
}

func (m *ProtoOASubscribeForTradingEventsReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOASubscribeForTradingEventsReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

// * Trading event subscription response
type ProtoOASubscribeForTradingEventsRes struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2003" json:"payloadType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOASubscribeForTradingEventsRes) Reset()         { *m = ProtoOASubscribeForTradingEventsRes{} }
func (m *ProtoOASubscribeForTradingEventsRes) String() string { return proto.CompactTextString(m) }
func (*ProtoOASubscribeForTradingEventsRes) ProtoMessage()    {}
func (*ProtoOASubscribeForTradingEventsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{3}
}

const Default_ProtoOASubscribeForTradingEventsRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_SUBSCRIBE_FOR_TRADING_EVENTS_RES

func (m *ProtoOASubscribeForTradingEventsRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOASubscribeForTradingEventsRes_PayloadType
}

// * Request which unsubscribes from trading events for specified account
type ProtoOAUnsubscribeFromTradingEventsReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2004" json:"payloadType,omitempty"`
	AccountId        *int64              `protobuf:"varint,2,req,name=accountId" json:"accountId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAUnsubscribeFromTradingEventsReq) Reset() {
	*m = ProtoOAUnsubscribeFromTradingEventsReq{}
}
func (m *ProtoOAUnsubscribeFromTradingEventsReq) String() string { return proto.CompactTextString(m) }
func (*ProtoOAUnsubscribeFromTradingEventsReq) ProtoMessage()    {}
func (*ProtoOAUnsubscribeFromTradingEventsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{4}
}

const Default_ProtoOAUnsubscribeFromTradingEventsReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_UNSUBSCRIBE_FROM_TRADING_EVENTS_REQ

func (m *ProtoOAUnsubscribeFromTradingEventsReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAUnsubscribeFromTradingEventsReq_PayloadType
}

func (m *ProtoOAUnsubscribeFromTradingEventsReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

// * Trading event unsubscription response
type ProtoOAUnsubscribeFromTradingEventsRes struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2005" json:"payloadType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAUnsubscribeFromTradingEventsRes) Reset() {
	*m = ProtoOAUnsubscribeFromTradingEventsRes{}
}
func (m *ProtoOAUnsubscribeFromTradingEventsRes) String() string { return proto.CompactTextString(m) }
func (*ProtoOAUnsubscribeFromTradingEventsRes) ProtoMessage()    {}
func (*ProtoOAUnsubscribeFromTradingEventsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{5}
}

const Default_ProtoOAUnsubscribeFromTradingEventsRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_UNSUBSCRIBE_FROM_TRADING_EVENTS_RES

func (m *ProtoOAUnsubscribeFromTradingEventsRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAUnsubscribeFromTradingEventsRes_PayloadType
}

// * Request for a list of accounts trading events from which are received
type ProtoOAGetSubscribedAccountsReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2006" json:"payloadType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAGetSubscribedAccountsReq) Reset()                    { *m = ProtoOAGetSubscribedAccountsReq{} }
func (m *ProtoOAGetSubscribedAccountsReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAGetSubscribedAccountsReq) ProtoMessage()               {}
func (*ProtoOAGetSubscribedAccountsReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

const Default_ProtoOAGetSubscribedAccountsReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_GET_SUBSCRIBED_ACCOUNTS_REQ

func (m *ProtoOAGetSubscribedAccountsReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAGetSubscribedAccountsReq_PayloadType
}

// * Response with a list of accounts trading events from which are received
type ProtoOAGetSubscribedAccountsRes struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2007" json:"payloadType,omitempty"`
	AccountId        []int64             `protobuf:"varint,2,rep,name=accountId" json:"accountId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAGetSubscribedAccountsRes) Reset()                    { *m = ProtoOAGetSubscribedAccountsRes{} }
func (m *ProtoOAGetSubscribedAccountsRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAGetSubscribedAccountsRes) ProtoMessage()               {}
func (*ProtoOAGetSubscribedAccountsRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

const Default_ProtoOAGetSubscribedAccountsRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_GET_SUBSCRIBED_ACCOUNTS_RES

func (m *ProtoOAGetSubscribedAccountsRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAGetSubscribedAccountsRes_PayloadType
}

func (m *ProtoOAGetSubscribedAccountsRes) GetAccountId() []int64 {
	if m != nil {
		return m.AccountId
	}
	return nil
}

// * Open Api Execution event
type ProtoOAExecutionEvent struct {
	PayloadType      *ProtoOAPayloadType   `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2016" json:"payloadType,omitempty"`
	ExecutionType    *ProtoOAExecutionType `protobuf:"varint,2,req,name=executionType,enum=ProtoOAExecutionType" json:"executionType,omitempty"`
	Order            *ProtoOAOrder         `protobuf:"bytes,3,req,name=order" json:"order,omitempty"`
	Position         *ProtoOAPosition      `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
	ReasonCode       *string               `protobuf:"bytes,5,opt,name=reasonCode" json:"reasonCode,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ProtoOAExecutionEvent) Reset()                    { *m = ProtoOAExecutionEvent{} }
func (m *ProtoOAExecutionEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAExecutionEvent) ProtoMessage()               {}
func (*ProtoOAExecutionEvent) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

const Default_ProtoOAExecutionEvent_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_EXECUTION_EVENT

func (m *ProtoOAExecutionEvent) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAExecutionEvent_PayloadType
}

func (m *ProtoOAExecutionEvent) GetExecutionType() ProtoOAExecutionType {
	if m != nil && m.ExecutionType != nil {
		return *m.ExecutionType
	}
	return ProtoOAExecutionType_OA_ORDER_ACCEPTED
}

func (m *ProtoOAExecutionEvent) GetOrder() *ProtoOAOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *ProtoOAExecutionEvent) GetPosition() *ProtoOAPosition {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *ProtoOAExecutionEvent) GetReasonCode() string {
	if m != nil && m.ReasonCode != nil {
		return *m.ReasonCode
	}
	return ""
}

// * A request for a new order
type ProtoOACreateOrderReq struct {
	PayloadType              *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2013" json:"payloadType,omitempty"`
	AccessToken              *string             `protobuf:"bytes,2,req,name=accessToken" json:"accessToken,omitempty"`
	AccountId                *int64              `protobuf:"varint,3,req,name=accountId" json:"accountId,omitempty"`
	SymbolName               *string             `protobuf:"bytes,4,req,name=symbolName" json:"symbolName,omitempty"`
	OrderType                *ProtoOAOrderType   `protobuf:"varint,5,req,name=orderType,enum=ProtoOAOrderType" json:"orderType,omitempty"`
	TradeSide                *ProtoTradeSide     `protobuf:"varint,6,req,name=tradeSide,enum=ProtoTradeSide" json:"tradeSide,omitempty"`
	Volume                   *int64              `protobuf:"varint,7,req,name=volume" json:"volume,omitempty"`
	RelativeStopLossInPips   *int32              `protobuf:"varint,8,opt,name=relativeStopLossInPips" json:"relativeStopLossInPips,omitempty"`
	RelativeTakeProfitInPips *int32              `protobuf:"varint,9,opt,name=relativeTakeProfitInPips" json:"relativeTakeProfitInPips,omitempty"`
	BaseSlippagePrice        *float64            `protobuf:"fixed64,10,opt,name=baseSlippagePrice" json:"baseSlippagePrice,omitempty"`
	SlippageInPips           *int64              `protobuf:"varint,11,opt,name=slippageInPips" json:"slippageInPips,omitempty"`
	LimitPrice               *float64            `protobuf:"fixed64,12,opt,name=limitPrice" json:"limitPrice,omitempty"`
	StopPrice                *float64            `protobuf:"fixed64,13,opt,name=stopPrice" json:"stopPrice,omitempty"`
	ExpirationTimestamp      *int64              `protobuf:"varint,14,opt,name=expirationTimestamp" json:"expirationTimestamp,omitempty"`
	StopLossPrice            *float64            `protobuf:"fixed64,15,opt,name=stopLossPrice" json:"stopLossPrice,omitempty"`
	TakeProfitPrice          *float64            `protobuf:"fixed64,16,opt,name=takeProfitPrice" json:"takeProfitPrice,omitempty"`
	Comment                  *string             `protobuf:"bytes,17,opt,name=comment" json:"comment,omitempty"`
	PositionId               *int64              `protobuf:"varint,18,opt,name=positionId" json:"positionId,omitempty"`
	TimeInForce              *ProtoTimeInForce   `protobuf:"varint,19,opt,name=timeInForce,enum=ProtoTimeInForce" json:"timeInForce,omitempty"`
	ClientOrderId            *string             `protobuf:"bytes,20,opt,name=clientOrderId" json:"clientOrderId,omitempty"`
	XXX_unrecognized         []byte              `json:"-"`
}

func (m *ProtoOACreateOrderReq) Reset()                    { *m = ProtoOACreateOrderReq{} }
func (m *ProtoOACreateOrderReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOACreateOrderReq) ProtoMessage()               {}
func (*ProtoOACreateOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

const Default_ProtoOACreateOrderReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_CREATE_ORDER_REQ

func (m *ProtoOACreateOrderReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOACreateOrderReq_PayloadType
}

func (m *ProtoOACreateOrderReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProtoOACreateOrderReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetSymbolName() string {
	if m != nil && m.SymbolName != nil {
		return *m.SymbolName
	}
	return ""
}

func (m *ProtoOACreateOrderReq) GetOrderType() ProtoOAOrderType {
	if m != nil && m.OrderType != nil {
		return *m.OrderType
	}
	return ProtoOAOrderType_OA_MARKET
}

func (m *ProtoOACreateOrderReq) GetTradeSide() ProtoTradeSide {
	if m != nil && m.TradeSide != nil {
		return *m.TradeSide
	}
	return ProtoTradeSide_BUY
}

func (m *ProtoOACreateOrderReq) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetRelativeStopLossInPips() int32 {
	if m != nil && m.RelativeStopLossInPips != nil {
		return *m.RelativeStopLossInPips
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetRelativeTakeProfitInPips() int32 {
	if m != nil && m.RelativeTakeProfitInPips != nil {
		return *m.RelativeTakeProfitInPips
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetBaseSlippagePrice() float64 {
	if m != nil && m.BaseSlippagePrice != nil {
		return *m.BaseSlippagePrice
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetSlippageInPips() int64 {
	if m != nil && m.SlippageInPips != nil {
		return *m.SlippageInPips
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetLimitPrice() float64 {
	if m != nil && m.LimitPrice != nil {
		return *m.LimitPrice
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetStopPrice() float64 {
	if m != nil && m.StopPrice != nil {
		return *m.StopPrice
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetExpirationTimestamp() int64 {
	if m != nil && m.ExpirationTimestamp != nil {
		return *m.ExpirationTimestamp
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetStopLossPrice() float64 {
	if m != nil && m.StopLossPrice != nil {
		return *m.StopLossPrice
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetTakeProfitPrice() float64 {
	if m != nil && m.TakeProfitPrice != nil {
		return *m.TakeProfitPrice
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetComment() string {
	if m != nil && m.Comment != nil {
		return *m.Comment
	}
	return ""
}

func (m *ProtoOACreateOrderReq) GetPositionId() int64 {
	if m != nil && m.PositionId != nil {
		return *m.PositionId
	}
	return 0
}

func (m *ProtoOACreateOrderReq) GetTimeInForce() ProtoTimeInForce {
	if m != nil && m.TimeInForce != nil {
		return *m.TimeInForce
	}
	return ProtoTimeInForce_GOOD_TILL_DATE
}

func (m *ProtoOACreateOrderReq) GetClientOrderId() string {
	if m != nil && m.ClientOrderId != nil {
		return *m.ClientOrderId
	}
	return ""
}

// * Cancel pending order request
type ProtoOACancelOrderReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2017" json:"payloadType,omitempty"`
	AccessToken      *string             `protobuf:"bytes,2,req,name=accessToken" json:"accessToken,omitempty"`
	AccountId        *int64              `protobuf:"varint,3,req,name=accountId" json:"accountId,omitempty"`
	OrderId          *int64              `protobuf:"varint,4,req,name=orderId" json:"orderId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOACancelOrderReq) Reset()                    { *m = ProtoOACancelOrderReq{} }
func (m *ProtoOACancelOrderReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOACancelOrderReq) ProtoMessage()               {}
func (*ProtoOACancelOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

const Default_ProtoOACancelOrderReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_CANCEL_ORDER_REQ

func (m *ProtoOACancelOrderReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOACancelOrderReq_PayloadType
}

func (m *ProtoOACancelOrderReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProtoOACancelOrderReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOACancelOrderReq) GetOrderId() int64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

// * Closing existing position request
type ProtoOAClosePositionReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2018" json:"payloadType,omitempty"`
	AccessToken      *string             `protobuf:"bytes,2,req,name=accessToken" json:"accessToken,omitempty"`
	AccountId        *int64              `protobuf:"varint,3,req,name=accountId" json:"accountId,omitempty"`
	PositionId       *int64              `protobuf:"varint,4,req,name=positionId" json:"positionId,omitempty"`
	Volume           *int64              `protobuf:"varint,5,req,name=volume" json:"volume,omitempty"`
	TimeInForce      *ProtoTimeInForce   `protobuf:"varint,6,opt,name=timeInForce,enum=ProtoTimeInForce" json:"timeInForce,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAClosePositionReq) Reset()                    { *m = ProtoOAClosePositionReq{} }
func (m *ProtoOAClosePositionReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAClosePositionReq) ProtoMessage()               {}
func (*ProtoOAClosePositionReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

const Default_ProtoOAClosePositionReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_CLOSE_POSITION_REQ

func (m *ProtoOAClosePositionReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAClosePositionReq_PayloadType
}

func (m *ProtoOAClosePositionReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProtoOAClosePositionReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOAClosePositionReq) GetPositionId() int64 {
	if m != nil && m.PositionId != nil {
		return *m.PositionId
	}
	return 0
}

func (m *ProtoOAClosePositionReq) GetVolume() int64 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *ProtoOAClosePositionReq) GetTimeInForce() ProtoTimeInForce {
	if m != nil && m.TimeInForce != nil {
		return *m.TimeInForce
	}
	return ProtoTimeInForce_GOOD_TILL_DATE
}

// * Amending existing position's stop loss and take profit
type ProtoOAAmendPositionStopLossTakeProfitReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2019" json:"payloadType,omitempty"`
	AccessToken      *string             `protobuf:"bytes,2,req,name=accessToken" json:"accessToken,omitempty"`
	AccountId        *int64              `protobuf:"varint,3,req,name=accountId" json:"accountId,omitempty"`
	PositionId       *int64              `protobuf:"varint,4,req,name=positionId" json:"positionId,omitempty"`
	StopLossPrice    *float64            `protobuf:"fixed64,5,opt,name=stopLossPrice" json:"stopLossPrice,omitempty"`
	TakeProfitPrice  *float64            `protobuf:"fixed64,6,opt,name=takeProfitPrice" json:"takeProfitPrice,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) Reset() {
	*m = ProtoOAAmendPositionStopLossTakeProfitReq{}
}
func (m *ProtoOAAmendPositionStopLossTakeProfitReq) String() string { return proto.CompactTextString(m) }
func (*ProtoOAAmendPositionStopLossTakeProfitReq) ProtoMessage()    {}
func (*ProtoOAAmendPositionStopLossTakeProfitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{12}
}

const Default_ProtoOAAmendPositionStopLossTakeProfitReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_AMEND_POSITION_SL_TP_REQ

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAAmendPositionStopLossTakeProfitReq_PayloadType
}

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) GetPositionId() int64 {
	if m != nil && m.PositionId != nil {
		return *m.PositionId
	}
	return 0
}

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) GetStopLossPrice() float64 {
	if m != nil && m.StopLossPrice != nil {
		return *m.StopLossPrice
	}
	return 0
}

func (m *ProtoOAAmendPositionStopLossTakeProfitReq) GetTakeProfitPrice() float64 {
	if m != nil && m.TakeProfitPrice != nil {
		return *m.TakeProfitPrice
	}
	return 0
}

// * Amending existing pending order request
type ProtoOAAmendOrderReq struct {
	PayloadType              *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2020" json:"payloadType,omitempty"`
	AccessToken              *string             `protobuf:"bytes,2,req,name=accessToken" json:"accessToken,omitempty"`
	AccountId                *int64              `protobuf:"varint,3,req,name=accountId" json:"accountId,omitempty"`
	OrderId                  *int64              `protobuf:"varint,4,req,name=orderId" json:"orderId,omitempty"`
	TimeInForce              *ProtoTimeInForce   `protobuf:"varint,5,opt,name=timeInForce,enum=ProtoTimeInForce,def=2" json:"timeInForce,omitempty"`
	LimitPrice               *float64            `protobuf:"fixed64,6,opt,name=limitPrice" json:"limitPrice,omitempty"`
	StopPrice                *float64            `protobuf:"fixed64,7,opt,name=stopPrice" json:"stopPrice,omitempty"`
	ExpirationTimestamp      *int64              `protobuf:"varint,8,opt,name=expirationTimestamp" json:"expirationTimestamp,omitempty"`
	MinVolume                *int64              `protobuf:"varint,9,opt,name=minVolume" json:"minVolume,omitempty"`
	StopLossPrice            *float64            `protobuf:"fixed64,10,opt,name=stopLossPrice" json:"stopLossPrice,omitempty"`
	TakeProfitPrice          *float64            `protobuf:"fixed64,11,opt,name=takeProfitPrice" json:"takeProfitPrice,omitempty"`
	RelativeStopLossInPips   *int32              `protobuf:"varint,12,opt,name=relativeStopLossInPips" json:"relativeStopLossInPips,omitempty"`
	RelativeTakeProfitInPips *int32              `protobuf:"varint,14,opt,name=relativeTakeProfitInPips" json:"relativeTakeProfitInPips,omitempty"`
	Comment                  *string             `protobuf:"bytes,15,opt,name=comment" json:"comment,omitempty"`
	XXX_unrecognized         []byte              `json:"-"`
}

func (m *ProtoOAAmendOrderReq) Reset()                    { *m = ProtoOAAmendOrderReq{} }
func (m *ProtoOAAmendOrderReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAAmendOrderReq) ProtoMessage()               {}
func (*ProtoOAAmendOrderReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

const Default_ProtoOAAmendOrderReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_AMEND_ORDER_REQ
const Default_ProtoOAAmendOrderReq_TimeInForce ProtoTimeInForce = ProtoTimeInForce_GOOD_TILL_CANCEL

func (m *ProtoOAAmendOrderReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAAmendOrderReq_PayloadType
}

func (m *ProtoOAAmendOrderReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProtoOAAmendOrderReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetOrderId() int64 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetTimeInForce() ProtoTimeInForce {
	if m != nil && m.TimeInForce != nil {
		return *m.TimeInForce
	}
	return Default_ProtoOAAmendOrderReq_TimeInForce
}

func (m *ProtoOAAmendOrderReq) GetLimitPrice() float64 {
	if m != nil && m.LimitPrice != nil {
		return *m.LimitPrice
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetStopPrice() float64 {
	if m != nil && m.StopPrice != nil {
		return *m.StopPrice
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetExpirationTimestamp() int64 {
	if m != nil && m.ExpirationTimestamp != nil {
		return *m.ExpirationTimestamp
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetMinVolume() int64 {
	if m != nil && m.MinVolume != nil {
		return *m.MinVolume
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetStopLossPrice() float64 {
	if m != nil && m.StopLossPrice != nil {
		return *m.StopLossPrice
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetTakeProfitPrice() float64 {
	if m != nil && m.TakeProfitPrice != nil {
		return *m.TakeProfitPrice
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetRelativeStopLossInPips() int32 {
	if m != nil && m.RelativeStopLossInPips != nil {
		return *m.RelativeStopLossInPips
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetRelativeTakeProfitInPips() int32 {
	if m != nil && m.RelativeTakeProfitInPips != nil {
		return *m.RelativeTakeProfitInPips
	}
	return 0
}

func (m *ProtoOAAmendOrderReq) GetComment() string {
	if m != nil && m.Comment != nil {
		return *m.Comment
	}
	return ""
}

// * Request subscribes for spots for specified account and symbol
type ProtoOASubscribeForSpotsReq struct {
	PayloadType      *ProtoOAPayloadType     `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2021" json:"payloadType,omitempty"`
	AccountId        *int64                  `protobuf:"varint,2,req,name=accountId" json:"accountId,omitempty"`
	AccessToken      *string                 `protobuf:"bytes,3,req,name=accessToken" json:"accessToken,omitempty"`
	SymblolName      *string                 `protobuf:"bytes,4,req,name=symblolName" json:"symblolName,omitempty"`
	TrendbarPeriod   []ProtoOATrendbarPeriod `protobuf:"varint,5,rep,name=trendbarPeriod,enum=ProtoOATrendbarPeriod" json:"trendbarPeriod,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *ProtoOASubscribeForSpotsReq) Reset()                    { *m = ProtoOASubscribeForSpotsReq{} }
func (m *ProtoOASubscribeForSpotsReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOASubscribeForSpotsReq) ProtoMessage()               {}
func (*ProtoOASubscribeForSpotsReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

const Default_ProtoOASubscribeForSpotsReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_SUBSCRIBE_FOR_SPOTS_REQ

func (m *ProtoOASubscribeForSpotsReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOASubscribeForSpotsReq_PayloadType
}

func (m *ProtoOASubscribeForSpotsReq) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *ProtoOASubscribeForSpotsReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *ProtoOASubscribeForSpotsReq) GetSymblolName() string {
	if m != nil && m.SymblolName != nil {
		return *m.SymblolName
	}
	return ""
}

func (m *ProtoOASubscribeForSpotsReq) GetTrendbarPeriod() []ProtoOATrendbarPeriod {
	if m != nil {
		return m.TrendbarPeriod
	}
	return nil
}

// * Spot subscription response
type ProtoOASubscribeForSpotsRes struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2022" json:"payloadType,omitempty"`
	SubscriptionId   *uint32             `protobuf:"varint,2,req,name=subscriptionId" json:"subscriptionId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOASubscribeForSpotsRes) Reset()                    { *m = ProtoOASubscribeForSpotsRes{} }
func (m *ProtoOASubscribeForSpotsRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoOASubscribeForSpotsRes) ProtoMessage()               {}
func (*ProtoOASubscribeForSpotsRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

const Default_ProtoOASubscribeForSpotsRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_SUBSCRIBE_FOR_SPOTS_RES

func (m *ProtoOASubscribeForSpotsRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOASubscribeForSpotsRes_PayloadType
}

func (m *ProtoOASubscribeForSpotsRes) GetSubscriptionId() uint32 {
	if m != nil && m.SubscriptionId != nil {
		return *m.SubscriptionId
	}
	return 0
}

// * Unsubscribes from spots for specified subscriptionId and accountId
type ProtoOAUnsubscribeFromSpotsReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2023" json:"payloadType,omitempty"`
	SubscriptionId   *uint32             `protobuf:"varint,2,opt,name=subscriptionId" json:"subscriptionId,omitempty"`
	SymblolName      *string             `protobuf:"bytes,3,opt,name=symblolName" json:"symblolName,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAUnsubscribeFromSpotsReq) Reset()                    { *m = ProtoOAUnsubscribeFromSpotsReq{} }
func (m *ProtoOAUnsubscribeFromSpotsReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAUnsubscribeFromSpotsReq) ProtoMessage()               {}
func (*ProtoOAUnsubscribeFromSpotsReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

const Default_ProtoOAUnsubscribeFromSpotsReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_UNSUBSCRIBE_FROM_SPOTS_REQ

func (m *ProtoOAUnsubscribeFromSpotsReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAUnsubscribeFromSpotsReq_PayloadType
}

func (m *ProtoOAUnsubscribeFromSpotsReq) GetSubscriptionId() uint32 {
	if m != nil && m.SubscriptionId != nil {
		return *m.SubscriptionId
	}
	return 0
}

func (m *ProtoOAUnsubscribeFromSpotsReq) GetSymblolName() string {
	if m != nil && m.SymblolName != nil {
		return *m.SymblolName
	}
	return ""
}

// * Spot unsubscription response
type ProtoOAUnsubscribeFromSpotsRes struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2024" json:"payloadType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAUnsubscribeFromSpotsRes) Reset()                    { *m = ProtoOAUnsubscribeFromSpotsRes{} }
func (m *ProtoOAUnsubscribeFromSpotsRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAUnsubscribeFromSpotsRes) ProtoMessage()               {}
func (*ProtoOAUnsubscribeFromSpotsRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

const Default_ProtoOAUnsubscribeFromSpotsRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_UNSUBSCRIBE_FROM_SPOTS_RES

func (m *ProtoOAUnsubscribeFromSpotsRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAUnsubscribeFromSpotsRes_PayloadType
}

// * Request for subscription by its id
type ProtoOAGetSpotSubscriptionReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2025" json:"payloadType,omitempty"`
	SubscriptionId   *uint32             `protobuf:"varint,2,req,name=subscriptionId" json:"subscriptionId,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAGetSpotSubscriptionReq) Reset()                    { *m = ProtoOAGetSpotSubscriptionReq{} }
func (m *ProtoOAGetSpotSubscriptionReq) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAGetSpotSubscriptionReq) ProtoMessage()               {}
func (*ProtoOAGetSpotSubscriptionReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

const Default_ProtoOAGetSpotSubscriptionReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_GET_SPOT_SUBSCRIPTION_REQ

func (m *ProtoOAGetSpotSubscriptionReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAGetSpotSubscriptionReq_PayloadType
}

func (m *ProtoOAGetSpotSubscriptionReq) GetSubscriptionId() uint32 {
	if m != nil && m.SubscriptionId != nil {
		return *m.SubscriptionId
	}
	return 0
}

// * SpotSubscription Response
type ProtoOAGetSpotSubscriptionRes struct {
	PayloadType      *ProtoOAPayloadType      `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2026" json:"payloadType,omitempty"`
	SpotSubscription *ProtoOASpotSubscription `protobuf:"bytes,2,req,name=spotSubscription" json:"spotSubscription,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ProtoOAGetSpotSubscriptionRes) Reset()                    { *m = ProtoOAGetSpotSubscriptionRes{} }
func (m *ProtoOAGetSpotSubscriptionRes) String() string            { return proto.CompactTextString(m) }
func (*ProtoOAGetSpotSubscriptionRes) ProtoMessage()               {}
func (*ProtoOAGetSpotSubscriptionRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

const Default_ProtoOAGetSpotSubscriptionRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_GET_SPOT_SUBSCRIPTION_RES

func (m *ProtoOAGetSpotSubscriptionRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAGetSpotSubscriptionRes_PayloadType
}

func (m *ProtoOAGetSpotSubscriptionRes) GetSpotSubscription() *ProtoOASpotSubscription {
	if m != nil {
		return m.SpotSubscription
	}
	return nil
}

// * Request for all subscriptions of specified account
type ProtoOAGetAllSpotSubscriptionsReq struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2027" json:"payloadType,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOAGetAllSpotSubscriptionsReq) Reset()         { *m = ProtoOAGetAllSpotSubscriptionsReq{} }
func (m *ProtoOAGetAllSpotSubscriptionsReq) String() string { return proto.CompactTextString(m) }
func (*ProtoOAGetAllSpotSubscriptionsReq) ProtoMessage()    {}
func (*ProtoOAGetAllSpotSubscriptionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{20}
}

const Default_ProtoOAGetAllSpotSubscriptionsReq_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_GET_ALL_SPOT_SUBSCRIPTIONS_REQ

func (m *ProtoOAGetAllSpotSubscriptionsReq) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAGetAllSpotSubscriptionsReq_PayloadType
}

// * Response with all account's spotSubscriptions
type ProtoOAGetAllSpotSubscriptionsRes struct {
	PayloadType       *ProtoOAPayloadType        `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2028" json:"payloadType,omitempty"`
	SpotSubscriptions []*ProtoOASpotSubscription `protobuf:"bytes,2,rep,name=spotSubscriptions" json:"spotSubscriptions,omitempty"`
	XXX_unrecognized  []byte                     `json:"-"`
}

func (m *ProtoOAGetAllSpotSubscriptionsRes) Reset()         { *m = ProtoOAGetAllSpotSubscriptionsRes{} }
func (m *ProtoOAGetAllSpotSubscriptionsRes) String() string { return proto.CompactTextString(m) }
func (*ProtoOAGetAllSpotSubscriptionsRes) ProtoMessage()    {}
func (*ProtoOAGetAllSpotSubscriptionsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{21}
}

const Default_ProtoOAGetAllSpotSubscriptionsRes_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_GET_ALL_SPOT_SUBSCRIPTIONS_RES

func (m *ProtoOAGetAllSpotSubscriptionsRes) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOAGetAllSpotSubscriptionsRes_PayloadType
}

func (m *ProtoOAGetAllSpotSubscriptionsRes) GetSpotSubscriptions() []*ProtoOASpotSubscription {
	if m != nil {
		return m.SpotSubscriptions
	}
	return nil
}

// * Spot event
type ProtoOASpotEvent struct {
	PayloadType      *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=ProtoOAPayloadType,def=2029" json:"payloadType,omitempty"`
	SubscriptionId   *uint32             `protobuf:"varint,2,req,name=subscriptionId" json:"subscriptionId,omitempty"`
	SymbolName       *string             `protobuf:"bytes,3,req,name=symbolName" json:"symbolName,omitempty"`
	BidPrice         *float64            `protobuf:"fixed64,4,opt,name=bidPrice" json:"bidPrice,omitempty"`
	AskPrice         *float64            `protobuf:"fixed64,5,opt,name=askPrice" json:"askPrice,omitempty"`
	Trendbar         []*ProtoOATrendbar  `protobuf:"bytes,6,rep,name=trendbar" json:"trendbar,omitempty"`
	Timestamp        *int64              `protobuf:"varint,7,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ProtoOASpotEvent) Reset()                    { *m = ProtoOASpotEvent{} }
func (m *ProtoOASpotEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtoOASpotEvent) ProtoMessage()               {}
func (*ProtoOASpotEvent) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{22} }

const Default_ProtoOASpotEvent_PayloadType ProtoOAPayloadType = ProtoOAPayloadType_OA_SPOT_EVENT

func (m *ProtoOASpotEvent) GetPayloadType() ProtoOAPayloadType {
	if m != nil && m.PayloadType != nil {
		return *m.PayloadType
	}
	return Default_ProtoOASpotEvent_PayloadType
}

func (m *ProtoOASpotEvent) GetSubscriptionId() uint32 {
	if m != nil && m.SubscriptionId != nil {
		return *m.SubscriptionId
	}
	return 0
}

func (m *ProtoOASpotEvent) GetSymbolName() string {
	if m != nil && m.SymbolName != nil {
		return *m.SymbolName
	}
	return ""
}

func (m *ProtoOASpotEvent) GetBidPrice() float64 {
	if m != nil && m.BidPrice != nil {
		return *m.BidPrice
	}
	return 0
}

func (m *ProtoOASpotEvent) GetAskPrice() float64 {
	if m != nil && m.AskPrice != nil {
		return *m.AskPrice
	}
	return 0
}

func (m *ProtoOASpotEvent) GetTrendbar() []*ProtoOATrendbar {
	if m != nil {
		return m.Trendbar
	}
	return nil
}

func (m *ProtoOASpotEvent) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoOAAuthReq)(nil), "ProtoOAAuthReq")
	proto.RegisterType((*ProtoOAAuthRes)(nil), "ProtoOAAuthRes")
	proto.RegisterType((*ProtoOASubscribeForTradingEventsReq)(nil), "ProtoOASubscribeForTradingEventsReq")
	proto.RegisterType((*ProtoOASubscribeForTradingEventsRes)(nil), "ProtoOASubscribeForTradingEventsRes")
	proto.RegisterType((*ProtoOAUnsubscribeFromTradingEventsReq)(nil), "ProtoOAUnsubscribeFromTradingEventsReq")
	proto.RegisterType((*ProtoOAUnsubscribeFromTradingEventsRes)(nil), "ProtoOAUnsubscribeFromTradingEventsRes")
	proto.RegisterType((*ProtoOAGetSubscribedAccountsReq)(nil), "ProtoOAGetSubscribedAccountsReq")
	proto.RegisterType((*ProtoOAGetSubscribedAccountsRes)(nil), "ProtoOAGetSubscribedAccountsRes")
	proto.RegisterType((*ProtoOAExecutionEvent)(nil), "ProtoOAExecutionEvent")
	proto.RegisterType((*ProtoOACreateOrderReq)(nil), "ProtoOACreateOrderReq")
	proto.RegisterType((*ProtoOACancelOrderReq)(nil), "ProtoOACancelOrderReq")
	proto.RegisterType((*ProtoOAClosePositionReq)(nil), "ProtoOAClosePositionReq")
	proto.RegisterType((*ProtoOAAmendPositionStopLossTakeProfitReq)(nil), "ProtoOAAmendPositionStopLossTakeProfitReq")
	proto.RegisterType((*ProtoOAAmendOrderReq)(nil), "ProtoOAAmendOrderReq")
	proto.RegisterType((*ProtoOASubscribeForSpotsReq)(nil), "ProtoOASubscribeForSpotsReq")
	proto.RegisterType((*ProtoOASubscribeForSpotsRes)(nil), "ProtoOASubscribeForSpotsRes")
	proto.RegisterType((*ProtoOAUnsubscribeFromSpotsReq)(nil), "ProtoOAUnsubscribeFromSpotsReq")
	proto.RegisterType((*ProtoOAUnsubscribeFromSpotsRes)(nil), "ProtoOAUnsubscribeFromSpotsRes")
	proto.RegisterType((*ProtoOAGetSpotSubscriptionReq)(nil), "ProtoOAGetSpotSubscriptionReq")
	proto.RegisterType((*ProtoOAGetSpotSubscriptionRes)(nil), "ProtoOAGetSpotSubscriptionRes")
	proto.RegisterType((*ProtoOAGetAllSpotSubscriptionsReq)(nil), "ProtoOAGetAllSpotSubscriptionsReq")
	proto.RegisterType((*ProtoOAGetAllSpotSubscriptionsRes)(nil), "ProtoOAGetAllSpotSubscriptionsRes")
	proto.RegisterType((*ProtoOASpotEvent)(nil), "ProtoOASpotEvent")
}

var fileDescriptor2 = []byte{
	// 1279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xe3, 0xc4,
	0x17, 0x97, 0x37, 0x4d, 0xb7, 0x99, 0x6c, 0xd2, 0xd4, 0xfd, 0x58, 0x6f, 0xbb, 0xdb, 0x7f, 0xd7,
	0xfb, 0x57, 0x55, 0x24, 0x94, 0x8b, 0x20, 0x04, 0x5a, 0x81, 0x90, 0x9b, 0xb8, 0x69, 0x44, 0x1a,
	0x87, 0xd8, 0x59, 0x21, 0x6e, 0x22, 0x27, 0x19, 0xca, 0xa8, 0x8e, 0xc7, 0x78, 0xdc, 0xaa, 0x05,
	0x09, 0x9e, 0x00, 0x71, 0xc7, 0x0d, 0x5c, 0xc0, 0x05, 0x0f, 0xc1, 0x4b, 0x20, 0xc4, 0x1d, 0x37,
	0x3c, 0x0b, 0x67, 0xc6, 0x76, 0x92, 0xba, 0x49, 0xeb, 0x76, 0x73, 0x97, 0xce, 0x39, 0x73, 0xce,
	0xef, 0xfc, 0xce, 0xc7, 0x9c, 0x1a, 0x6d, 0x1a, 0x1e, 0x76, 0x35, 0x8f, 0x9c, 0x60, 0xc6, 0xec,
	0x53, 0xcc, 0xca, 0x9e, 0x4f, 0x03, 0xba, 0xbd, 0x1d, 0x1f, 0xd3, 0x21, 0x76, 0x12, 0xb2, 0x67,
	0x55, 0x3a, 0x1a, 0x51, 0x77, 0x86, 0x48, 0xa5, 0xa8, 0xd8, 0xe6, 0x3f, 0x0c, 0x4d, 0x3b, 0x0f,
	0xbe, 0xea, 0xe0, 0xaf, 0xe5, 0xf7, 0x51, 0xde, 0xb3, 0xaf, 0x1c, 0x6a, 0x0f, 0xad, 0x2b, 0x0f,
	0x2b, 0xd2, 0x9e, 0x74, 0x50, 0xac, 0xac, 0x97, 0x23, 0xad, 0xf6, 0x44, 0xf4, 0x3a, 0x6f, 0x68,
	0x3d, 0xad, 0x6b, 0x1d, 0xf7, 0x3a, 0xfa, 0x67, 0x72, 0x09, 0xad, 0x0c, 0x1c, 0x82, 0xdd, 0xa0,
	0x31, 0x54, 0x1e, 0xed, 0x3d, 0x3a, 0xc8, 0xc9, 0x1b, 0xe8, 0x49, 0x78, 0x62, 0xe2, 0x81, 0x8f,
	0x03, 0x25, 0xc3, 0x4f, 0xd5, 0x7a, 0xc2, 0x21, 0x7b, 0x98, 0x43, 0x53, 0xfd, 0x45, 0x42, 0xaf,
	0x22, 0x1d, 0xf3, 0xbc, 0xcf, 0x06, 0x3e, 0xe9, 0xe3, 0x23, 0xea, 0x5b, 0xbe, 0x3d, 0x24, 0xee,
	0xa9, 0x7e, 0x01, 0x8e, 0x19, 0x8f, 0xe7, 0x24, 0xb5, 0xf9, 0x57, 0x60, 0xde, 0xec, 0x1e, 0x9a,
	0xd5, 0x4e, 0xe3, 0x50, 0xef, 0x1d, 0x19, 0x9d, 0x9e, 0xd5, 0xd1, 0x6a, 0x8d, 0x56, 0xbd, 0xa7,
	0xbf, 0xd1, 0x5b, 0x96, 0x29, 0xe2, 0x5c, 0x43, 0x39, 0x7b, 0x30, 0xa0, 0xe7, 0xe3, 0x40, 0x33,
	0xf2, 0x3a, 0xca, 0xc3, 0x11, 0xf0, 0x6a, 0xd1, 0x33, 0xec, 0x46, 0x71, 0x06, 0x69, 0xd0, 0xb1,
	0xc5, 0xa2, 0x33, 0xd5, 0x1f, 0x24, 0xb4, 0x1f, 0xdd, 0xed, 0xba, 0x6c, 0xec, 0xd8, 0xa7, 0xa3,
	0x1b, 0xbc, 0xb4, 0x53, 0x7b, 0xde, 0x07, 0xcf, 0xdd, 0xd6, 0x94, 0xef, 0x8e, 0x71, 0x92, 0x8e,
	0x1a, 0xf5, 0x9b, 0x94, 0x70, 0xd8, 0xc2, 0xe1, 0x98, 0xea, 0x19, 0xfa, 0x5f, 0x74, 0xbb, 0x8e,
	0x83, 0x71, 0x12, 0x86, 0x5a, 0x08, 0x51, 0x70, 0x70, 0x9c, 0xda, 0xe9, 0x2e, 0x38, 0xad, 0xeb,
	0xd6, 0x24, 0x03, 0xb5, 0x9e, 0x56, 0xad, 0x1a, 0xdd, 0x28, 0x76, 0xf5, 0xbb, 0xbb, 0x9c, 0xb1,
	0x85, 0x39, 0x33, 0x93, 0x44, 0x67, 0x80, 0xe8, 0x7f, 0x24, 0xb4, 0x19, 0x59, 0xd2, 0x2f, 0xf1,
	0xe0, 0x3c, 0x20, 0xd4, 0x15, 0xe4, 0xca, 0x1f, 0xa5, 0x76, 0x2b, 0x83, 0x5b, 0xfd, 0x73, 0xbd,
	0xda, 0xb5, 0x1a, 0x46, 0x2b, 0x64, 0x52, 0x7e, 0x17, 0x15, 0x70, 0x6c, 0x4f, 0xdc, 0xe7, 0x79,
	0x2d, 0x56, 0x36, 0xcb, 0x49, 0x67, 0x5c, 0x28, 0x3f, 0x47, 0x59, 0xea, 0x0f, 0xb1, 0x2f, 0x7a,
	0x20, 0x5f, 0x29, 0xc4, 0x5a, 0x06, 0x3f, 0x94, 0x55, 0xb4, 0xe2, 0x51, 0x46, 0xb8, 0xb6, 0xb2,
	0x04, 0x30, 0xf2, 0x95, 0xd2, 0x18, 0x46, 0x74, 0x2e, 0xcb, 0x08, 0xf9, 0xd8, 0x66, 0xd4, 0xad,
	0xc2, 0xb0, 0x52, 0xb2, 0xa0, 0x95, 0x53, 0xff, 0x58, 0x1a, 0xc7, 0x56, 0x05, 0x61, 0x80, 0x85,
	0x39, 0x9e, 0xbf, 0x8f, 0x53, 0xc7, 0xb6, 0x0e, 0xb1, 0x55, 0x3b, 0xba, 0x66, 0xe9, 0x3d, 0xa3,
	0x53, 0xd3, 0x3b, 0xa2, 0x60, 0x13, 0x8d, 0x1b, 0x8e, 0xad, 0x6b, 0xe4, 0x66, 0x44, 0x83, 0x03,
	0x28, 0x76, 0x35, 0xea, 0x53, 0xa7, 0x65, 0x8f, 0x30, 0x40, 0xe7, 0x6a, 0xff, 0x47, 0x39, 0x11,
	0xaa, 0x70, 0x9c, 0x15, 0xa4, 0xac, 0x5d, 0x0b, 0x57, 0x10, 0xa2, 0xa2, 0x5c, 0x00, 0x95, 0x8e,
	0x4d, 0x02, 0xd1, 0x2c, 0x0b, 0xad, 0xd5, 0x50, 0xcb, 0x8a, 0x8f, 0xe5, 0x22, 0x5a, 0xbe, 0xa0,
	0xce, 0x39, 0x58, 0x7e, 0x2c, 0xbc, 0xed, 0xa2, 0x2d, 0x1f, 0x3b, 0x76, 0x40, 0x2e, 0xb0, 0x19,
	0x50, 0xaf, 0x49, 0x19, 0x6b, 0xb8, 0x6d, 0xe2, 0x31, 0x65, 0x05, 0xe2, 0xcb, 0xca, 0x7b, 0x48,
	0x89, 0xe5, 0x96, 0x7d, 0x86, 0xc1, 0xda, 0x97, 0x24, 0x88, 0x34, 0x72, 0x42, 0xe3, 0x19, 0x5a,
	0xeb, 0xdb, 0x0c, 0x9b, 0x0e, 0xf1, 0x3c, 0x98, 0xf5, 0x6d, 0x9f, 0x0c, 0xb0, 0x82, 0x40, 0x24,
	0xc9, 0x5b, 0xa8, 0xc8, 0xa2, 0xe3, 0xe8, 0x4a, 0x1e, 0xce, 0x45, 0x88, 0x0e, 0x19, 0x91, 0x20,
	0xd4, 0x7d, 0x22, 0x74, 0x81, 0x09, 0x06, 0x00, 0xc2, 0xa3, 0x82, 0x38, 0xda, 0x41, 0xeb, 0xf8,
	0xd2, 0x23, 0xbe, 0x2d, 0x52, 0x4e, 0x46, 0x98, 0x05, 0xf6, 0xc8, 0x53, 0x8a, 0xc2, 0xc6, 0x26,
	0x2a, 0xb0, 0x08, 0x70, 0x78, 0x67, 0x55, 0xdc, 0x79, 0x8a, 0x56, 0x83, 0x31, 0xce, 0x50, 0x50,
	0x12, 0x82, 0x55, 0xf4, 0x78, 0x00, 0x0f, 0x13, 0x14, 0xa9, 0xb2, 0xc6, 0x13, 0xcd, 0x41, 0xc4,
	0x05, 0x02, 0xdc, 0xcb, 0xc2, 0xe8, 0x3e, 0xca, 0x07, 0xe0, 0xa7, 0xe1, 0xc2, 0xf4, 0x84, 0x9b,
	0xeb, 0x22, 0xc5, 0x11, 0xd3, 0xd6, 0x44, 0xc0, 0x9d, 0x87, 0xaf, 0x8d, 0x20, 0x1f, 0xae, 0x6f,
	0x88, 0xda, 0xf9, 0x71, 0xd2, 0x17, 0x55, 0xdb, 0x1d, 0x60, 0xe7, 0xa1, 0xb5, 0xa3, 0xb5, 0xaa,
	0x7a, 0xf3, 0x01, 0xb5, 0x03, 0x41, 0xd2, 0x08, 0xd1, 0x92, 0x18, 0x89, 0x7f, 0x4a, 0xe8, 0x69,
	0x8c, 0xc8, 0xa1, 0x0c, 0xc7, 0xa5, 0xcf, 0x31, 0x7d, 0x92, 0x1a, 0xd3, 0x26, 0xc7, 0xd4, 0x34,
	0x4c, 0xbd, 0xd7, 0x36, 0xcc, 0x86, 0x68, 0xd8, 0x7b, 0x56, 0xf4, 0x14, 0xd3, 0x02, 0xd8, 0x54,
	0x1d, 0x66, 0xc5, 0xdf, 0x09, 0xe6, 0x97, 0xe7, 0x30, 0xaf, 0xfe, 0x2b, 0xa1, 0x77, 0xe2, 0x27,
	0x1d, 0x92, 0x39, 0x8c, 0x03, 0x8a, 0x8b, 0x77, 0x52, 0xa4, 0x3c, 0x44, 0x3d, 0x75, 0x88, 0x3b,
	0xfc, 0xb5, 0x3f, 0xd1, 0x5b, 0xb5, 0x49, 0x88, 0x66, 0xb3, 0x67, 0xb5, 0xdf, 0x3a, 0xd0, 0x1b,
	0x75, 0x9a, 0x9d, 0x57, 0xa7, 0x3c, 0x66, 0x49, 0xfd, 0x2d, 0x83, 0x36, 0xa6, 0x03, 0x1c, 0x97,
	0xd0, 0xfd, 0x46, 0x6b, 0x18, 0xcb, 0xdb, 0x57, 0x90, 0xfc, 0xe1, 0xf5, 0xc4, 0x64, 0xe7, 0x24,
	0xe6, 0x75, 0xa9, 0x6e, 0x18, 0xb5, 0x9e, 0xd5, 0x68, 0x36, 0xa3, 0xf2, 0x4d, 0x74, 0xf9, 0xf2,
	0xcd, 0x2e, 0x7f, 0x7c, 0x5b, 0x97, 0xaf, 0x88, 0x86, 0x04, 0xfd, 0x11, 0x71, 0xdf, 0x84, 0x95,
	0x92, 0x9b, 0xdd, 0xf8, 0x68, 0x1e, 0xa1, 0x79, 0x21, 0x98, 0x3f, 0xe1, 0x9e, 0xdc, 0x39, 0xe1,
	0x8a, 0x42, 0x63, 0x6a, 0x74, 0xac, 0x8a, 0x3e, 0xff, 0x4b, 0x42, 0x3b, 0x33, 0xf6, 0x2d, 0xd3,
	0xa3, 0xe1, 0x4b, 0x5f, 0x4b, 0x9d, 0xaa, 0xed, 0x1b, 0x7b, 0x96, 0xd9, 0x36, 0xee, 0xb7, 0xfc,
	0xf1, 0x43, 0xfe, 0x60, 0x38, 0xd7, 0x5e, 0x8c, 0x32, 0x2a, 0x06, 0x3e, 0x94, 0x4f, 0xdf, 0xf6,
	0xdb, 0xd8, 0x27, 0x74, 0x08, 0x99, 0xcb, 0x00, 0x8a, 0xad, 0x18, 0x85, 0x75, 0x4d, 0xaa, 0x7e,
	0x7b, 0x5b, 0x44, 0x6c, 0x21, 0x11, 0x99, 0xe2, 0x3d, 0x08, 0xad, 0x7b, 0x51, 0x8f, 0xf0, 0xb0,
	0x0a, 0xea, 0x4f, 0x12, 0xda, 0x9d, 0xbd, 0xb9, 0x8d, 0x29, 0xad, 0xa7, 0x06, 0xf0, 0x62, 0xd6,
	0xc6, 0x36, 0x61, 0x75, 0x16, 0x06, 0xe9, 0xa0, 0x90, 0x64, 0x31, 0x23, 0x12, 0x4d, 0xee, 0xc0,
	0xc5, 0x16, 0x85, 0xcb, 0x54, 0xbf, 0x47, 0x2f, 0xa6, 0x76, 0x3a, 0x30, 0x6f, 0x4e, 0xa1, 0xe4,
	0x0c, 0x1c, 0xa5, 0xf6, 0xf4, 0x3c, 0xde, 0xe8, 0xc0, 0x78, 0x9c, 0x8b, 0xf6, 0x78, 0x6a, 0xcf,
	0x4b, 0xc2, 0xcf, 0xd2, 0xed, 0x08, 0xd8, 0x82, 0x10, 0x98, 0x72, 0x05, 0x95, 0x58, 0xc2, 0xbc,
	0xc0, 0x90, 0xaf, 0x28, 0xb1, 0xb1, 0xa4, 0x7b, 0xd5, 0x43, 0x2f, 0x27, 0xe0, 0x34, 0xc7, 0x49,
	0x2a, 0x88, 0x22, 0xf9, 0x34, 0x35, 0xc0, 0x97, 0x11, 0x40, 0x0d, 0xc6, 0xd5, 0x0d, 0x90, 0xe1,
	0x92, 0xfd, 0xbb, 0x74, 0xb7, 0x4b, 0xb6, 0x48, 0x97, 0xa6, 0xfc, 0x1e, 0x5a, 0x4b, 0x12, 0xc3,
	0xc4, 0xca, 0x7d, 0x1b, 0x33, 0x7f, 0x4b, 0xa8, 0x34, 0x25, 0x0b, 0xf7, 0xf0, 0x0f, 0x52, 0xc3,
	0x2a, 0xf0, 0x7e, 0xe5, 0x70, 0xc2, 0x15, 0x7c, 0x4e, 0x75, 0x24, 0xb6, 0xd2, 0x70, 0xf0, 0xc0,
	0x7f, 0xe1, 0x7d, 0x32, 0x0c, 0x67, 0xed, 0x92, 0x98, 0xb5, 0x70, 0x62, 0xb3, 0xb3, 0xe9, 0x77,
	0x0e, 0xd6, 0xf0, 0x78, 0x0e, 0xc1, 0x13, 0x90, 0x99, 0x5e, 0xc3, 0xe3, 0x09, 0xc4, 0x07, 0x5d,
	0x30, 0x9e, 0xfb, 0x62, 0x2d, 0x3d, 0x3c, 0x46, 0x2a, 0x8c, 0xdc, 0xf2, 0xa5, 0xd8, 0x67, 0xfd,
	0xf0, 0xf3, 0xc1, 0x80, 0x3a, 0xe1, 0x8f, 0x32, 0xf5, 0xb0, 0x6b, 0x7b, 0xe4, 0x50, 0xa9, 0x52,
	0x37, 0xb0, 0x89, 0x8b, 0xfd, 0xc4, 0x67, 0x8a, 0xb6, 0xf4, 0x45, 0x66, 0xc4, 0x4e, 0x7f, 0x95,
	0xa4, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xf2, 0x53, 0xa8, 0xc2, 0x10, 0x00, 0x00,
}
